version: 1.0.{build}
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: .\build.ps1
deploy:
- provider: NuGet
  api_key:
    secure: M6ahLYqDdpC2Whn/9Q/VU9AMb8P0rcz87+rmHDLYfi9Bl9gzGHA1vwL6Xh4DTfGR
  on:
    appveyor_repo_tag: true